####
# ATENTION:
# Replace all occurences of test-api with your project's name
####

# v2 sintax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  test-api-postgres-data:
    driver: local

  # MySQL Data
  test-api-mysql-data:
    driver: local

  # Redis Data
  test-api-redis-data:
    driver: local

services:
  # Postgres (9.5)
  postgres:
    image: ambientum/postgres:9.6
    container_name: test-api-postgres
    volumes:
      - test-api-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test-api
      - POSTGRES_DB=test-api
      - POSTGRES_USER=test-api

  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: test-api-mysql
    volumes:
      - test-api-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test-api
      - MYSQL_DATABASE=test-api
      - MYSQL_USER=test-api
      - MYSQL_PASSWORD=test-api

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: test-api-redis
    command: --appendonly yes
    volumes:
      - test-api-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.0-caddy
    container_name: test-api-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: test-api-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache